### ISSUE TITLE
fieldset content not hidden in chrome

### ISSUE THREAD

**Issue by gradel** [matthiask/django-content-editor#15]
Hi,
hiding a fieldset by double-clicking or using the "hide all elements" checkbox works in FF.
In current chrome it somehow collapses but the contents don't vanish and may make the save buttons unusable.
Tested in chrome and Brave browser and django-content-editor releases from 2.0 throughout 3.0.6
and three different feincms3 installations.
Looks like setting max-height to 0 is not sufficient here:
https://github.com/matthiask/django-content-editor/blob/dd90e4e01a3cea2ae8039983833af134a911fb03/content_editor/static/content_editor/content_editor.css#L131
Replacing max-height with height solves the issue for me now.

**Comment by matthiask** [comment]
Strange. This is a screenshot using Chrome and django-content-editor 3.0.6:

![image](https://user-images.githubusercontent.com/2627/100425369-5b96d400-308f-11eb-8aa4-93046a427ab6.png)

It seems to work. Adding more CSS properties isn't a problem but I'd like to understand the reasons first. 🤔

**Comment by sha-red** [comment]
Just a guess: Do you have any kind of adblocker running?

**Comment by matthiask** [comment]
I have Firefox with tracking protection and uBlock Origin in both browsers. The blocker does not block anything on this page. A different blocker might still cause this, of course.

**Comment by sha-red** [comment]
It might depend on which filter lists/rules are active, also the cosmetic filtering might interfere (just asking @gradel: did you try switching off uBlock etc?; I had this kind of problems with django-content-editor, too. I keep forgetting that those plugins tinker with web pages).

**Comment by gradel** [comment]
Yes, in chrome I have AdBlockPlus, Ghostery and Privacy Badger as potentially blocking add-ons. Deactivating all three does not avoid the issue. But in a addon-free vivaldi browser its working perfectly fine.
![Auswahl_102](https://user-images.githubusercontent.com/635870/100452926-60bd4880-30ba-11eb-8d9a-f520136de14f.png)
This is how it actually looks with a plain feincms3 install. All but one network calls are 200. You can see it here together with all console logs when loading the page.

**Comment by gradel** [comment]
Also no problem in addon-free chromium but, as said, in addon-free brave browser the same issue.

**Comment by matthiask** [comment]
I looked at the code. I'm using `max-height` there because I want to animate the fieldset when it is closing. We *could* switch to `height` but then we'd have to calculate and assign the height using JavaScript and I'd like to avoid that.

What we could do though is assign `display:none` *after* the transition finishes; I think that would be fine. `display:none` cannot be set initially though because some widgets will not initialize themselves correctly.

**Comment by gradel** [comment]
When I change max-height to height in the transition as well as in the collapsed rule, at first sight all works well. In uncollapsed state height is unset and automatically assigned.

**Comment by sha-red** [comment]
Related bugin Chrome?

https://bugs.chromium.org/p/chromium/issues/detail?id=1151858

**Comment by matthiask** [comment]
`height` works fine but the collapsing animation doesn't seem to work anymore? Animating from `height:auto` to `height:0` does not seem to be supported very well.

**Comment by gradel** [comment]
@matthiask you are right. Assuming that its caused by this mentioned chrome bug we should perhaps wait how this issue gets handled there.

**Comment by matthiask** [comment]
It seems the bug has been fixed in the meantime. 

We could of course transition to `max-height: 30px` on the `div.inline-related` element so that we do not hit the `fieldset` bug. Or we could listen for the `transitionend` event and apply `display:none`, and of course also remove `display:none` when going in the other direction again. But I'm not sure it's worth it?

**Comment by matthiask** [comment]
Also, this might work well: https://gist.github.com/ryanand26/7118582

(using a keyframe animation which applies `display:none` during the last 1%)

**Comment by sha-red** [comment]
Refering to PEP20 / 2 I would suggest to set display: none at the end of the transition anyway.

**Comment by matthiask** [comment]
I don't disagree but you cannot just call `.toggleClass(".for-deletion")` and `.toggleClass("collapsed")` then. You'll have to add more code to work around a bug which only existed in one browser in one version in one specific combination of HTML element and CSS property. That's not very beautiful to me.

**Comment by sha-red** [comment]
I am sorry that I am only superficially involved!

What about transitioning to "visibility: none" and back to "visiblity: visible"? Look fine (at first look) in Chromium.

**Comment by matthiask** [comment]
Interesting, this seems to work well. @gradel Could you test this patch please? The animation still works and it doesn't seem to break anything else.

```
diff --git a/content_editor/static/content_editor/content_editor.css b/content_editor/static/content_editor/content_editor.css
index c892552a..b0ee2afb 100644
--- a/content_editor/static/content_editor/content_editor.css
+++ b/content_editor/static/content_editor/content_editor.css
@@ -129,6 +129,7 @@ html {
 .order-machine .inline-related.for-deletion fieldset,
 .order-machine .inline-related.collapsed fieldset {
   max-height: 0;
+  visibility: hidden;
 }

 .machine-message {
```

**Comment by sha-red** [comment]
You should add a visibility:visible to the original state maybe so that the CSS transition is explicit.

**Comment by gradel** [comment]
Yes, this patch works fine. Just for the chrome version with this bug the 0.2s may be a bit to long for a perfect transition, but that would really be nitpicking ;)
