### ISSUE TITLE
Using django-filers drag & drop for images not possible

### ISSUE THREAD

**Issue by gradel** [matthiask/django-content-editor#16]
Hi,
i'm using django-filer for images as plugin in feincms3, which gives users the ability to drag & drop images into its file upload field.
This does not work with django-content-editor since the content-editor js handles the drop event and errors since there is no row which is marked as dragged:
https://github.com/matthiask/django-content-editor/blob/dd90e4e01a3cea2ae8039983833af134a911fb03/content_editor/static/content_editor/content_editor.js#L92
This event is not fired, so there is no row defined in:
https://github.com/matthiask/django-content-editor/blob/dd90e4e01a3cea2ae8039983833af134a911fb03/content_editor/static/content_editor/content_editor.js#L278
In a quick try I made the event listeners for dragover and drop dependent from the existence of window.__fs_dragging  and it seems to work. But i'm not really in such complex javascripts, so this is more of a question than an issue, wether you would see such a patch as a viable solution for me in my projects or a way to incorporate a solution for this in django-content-editor itself?

**Comment by matthiask** [comment]
@gradel That is definitely something which I would like to integrate into django-content-editor. If you have a thing which works for you please submit a pull request! We can iterate on it.

**Comment by matthiask** [comment]
Thanks, this should be fixed now and will soon be released. I'm thinking about waiting for a resolution of #15.

**Comment by gradel** [comment]
Thanks for this and your great work in general!
