### ISSUE TITLE
CKEditor Plugin Issues

### ISSUE THREAD

**Issue by doolijb** [matthiask/django-content-editor#19]
Hello,

I followed the doc instructions for the CKEditor plugin how-ever after several hours of troubleshooting, no dice.

I also installed a fresh environment with only django-ckeditor and django-content-editor and am having no luck.

Python 3.8, latest Django

Hate to turn to you but I'm hoping that maybe it's just a simple discrepancy between versions or docs. Thanks!

**Comment by matthiask** [comment]
Oh shoot, I think the documented JS has errors. 

Does it work if you set `default_attrs = {"data-type": "ckeditortype"}` instead of the documented `default_attrs = {"class": "richtext"}` ?

The JS code assumes django-ckeditor, but the Admin and Forms example uses CKEditor from a CDN.

**Comment by doolijb** [comment]
That did it, thanks!
