### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by m-sanders** [matthiask/django-content-editor#3]
> Everything here works alright, but is still subject to change. Some additional real-world testing has to happen before the code can be declared 1.0-ready. Also, additional docs and more tests.

Hello. I am keen to use this but hesitant due to the above. Any ideas how far you are off 1.0?

**Comment by matthiask** [comment]
I should just release the current state of things as 1.0! No substantial changes since early September despite heavy use give me lots of confidence that the code is actually much more stable than the version number suggests.

**Comment by matthiask** [comment]
There you go: https://pypi.python.org/pypi/django-content-editor/1.0.0
