### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by MrKrautee** [matthiask/django-content-editor#8]
`(.venv) 9:41:kraut@krautbox ~ % pip install django-content-editor`
`Collecting django-content-editor`

It stops/stays at `Collecting django-content-editor` and nothing happens.

using:
- Python 3.6.3
- pip 9.0.1
- clone from current django-content-editor master branch.
- Archlinux: Linux 4.13.11-1-ARCH x86_64 GNU/Linux
- fresh/new venv  ( `python -m venv ./.venv` )

**Comment by MrKrautee** [comment]
Seems to be a local problem. Using no cache dir, installation works like expected:
`(.venv) 9:41:kraut@krautbox ~ % pip install django-content-editor --no-cache-dir`

Nevertheless why it only happens installing content-editor. There was no problem installing other packages.
hm ??

**Comment by matthiask** [comment]
Hmm very strange. This sometimes happens to me when I have bad connectivity, but still interesting that it only happens with this particular package. I don't think I'm doing anything outlandish in `setup.py` at all...

**Comment by MrKrautee** [comment]
my pip cache got corrupted ( `~/.config/pip/http` ).
after deleting it, pip works as expected ...

i dont how this could happen, i never touched the cache dir.
i did nothing special/ uncommon using pip.
